spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/api_course
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        ddl-auto: false
  profiles:
    active: local
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  servlet:
    session:
      timeout: 60m
