CREATE TABLE IF NOT EXISTS users
(
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name varchar(30) NOT NULL,
    second_name varchar(30) NOT NULL,
    email varchar(50) NOT NULL UNIQUE,
    password text  NOT NULL,
    role varchar(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS blogs
(
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    description text NOT NULL,
    user_id int NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS blog_posts
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blog_id int REFERENCES blogs (id),
    content text NOT NULL,
    create_date TIMESTAMP NOT NULL,
    edit_date TIMESTAMP NOT NULL,
    FOREIGN KEY (blog_id) REFERENCES blogs (id) ON DELETE CASCADE
);